### ISSUE TITLE
Detect embeddings and LoRA trigger words before tokenization

### ISSUE THREAD

**Issue by rockerBOO** [scruffynerf/prompt_hacker#2]
Embeddings and LoRA trigger words should be treated separately of the tokenization, so they don't get split apart.

For embeddings, it may be possible to pass each word (separated by spaces) to see if it is a part of the embedding_db 

```python
from modules import sd_hijack
words = prompt.split(" ")
for word in words:
  if word in sd_hijack.embedding_db.word_embeddings.keys():
     # word is embedding
  else: 
     # tokenize this
```

LoRA I haven't found anything in the code, yet, that has the trigger word in it.

**Comment by scruffynerf** [comment]
the above was a good idea, and I adapted it (the sd_hijack module was slightly wrong) but the full code is now live and works.

Thanks!
